version: '2'

services:
  player:
    network_mode: "host"
    container_name: printer
    image: "arupiot/hsoe-printer:latest"
    privileged: true
    volumes:
      - /opt/images:/opt/images
      - /var/run/dbus:/var/run/dbus
      - /dev/bus/usb:/dev/bus/usb
      - config:/etc/cups
      - cache:/var/cache/cups
      - log:/var/log/cups
    restart: always
    ports:
      - "631:631"
    environment:
      - PRINTER_NAME=tmt
      - IMAGES_PATH=/opt/images
      - IMAGES_EXT=.png
      - PRINTING_INTERVAL=1200
  build:
    network: host
